#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff24283b
yabai -m config status_bar_foreground_color  0xffa9b1d6
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         1
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xffbb9af7
yabai -m config normal_window_border_color   0xff565f89
yabai -m config insert_window_border_color   0xffe0af68
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  45
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   10

yabai -m space 1 --label "Web"
yabai -m space 2 --label "Chat"
yabai -m space 3 --label "Music"
yabai -m space 4 --label "Dev"

yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^TablePlus$" manage=off

echo "yabai configuration loaded.."
