#!/usr/bin/env sh

# Load scripting addition (needs /private/etc/sudoers.d/yabai setup):
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bar settings
yabai -m config status_bar off
yabai -m config status_bar_text_font "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color 0xff24283b
yabai -m config status_bar_foreground_color 0xffa9b1d6
yabai -m config status_bar_space_icon_strip I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip  
yabai -m config status_bar_space_icon 
yabai -m config status_bar_clock_icon 

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow on
yabai -m config window_border on
yabai -m config window_border_blur off
yabai -m config window_border_placement inset
yabai -m config window_border_width 4
yabai -m config window_border_radius 1
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color 0xffbb9af7
yabai -m config normal_window_border_color 0xff565f89
yabai -m config insert_window_border_color 0xffe0af68
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10
yabai -m config external_bar all:40:0

yabai -m space 1 --label "Web"
yabai -m space 2 --label "Chat"
yabai -m space 3 --label "Music"
yabai -m space 4 --label "Dev"

yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^TablePlus$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Headset$" manage=off

# This focuses the previous window if a window is not currently focused, such as when a floating window is minimized
# https://github.com/koekeishiya/yabai/issues/1212#issuecomment-1107854658
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

echo "Loaded yabai"
